In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
import pandas as pd
import time
from datetime import datetime
import re

In [2]:
categories = {
    '정치': 'https://news.naver.com/section/100',
    '경제': 'https://news.naver.com/section/101',
    '사회': 'https://news.naver.com/section/102',
    '생활/문화': 'https://news.naver.com/section/103',
    'IT/과학': 'https://news.naver.com/section/105',
    '세계': 'https://news.naver.com/section/104'
}

NUM_ARTICLES_PER_CATEGORY = 10

In [7]:
service = Service(ChromeDriverManager().install())
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

driver = webdriver.Chrome(service=service, options=options)

In [8]:
def get_article_links(driver, category_url, num_articles):
    driver.get(category_url)
    time.sleep(3)

    article_links = []

    try:
        selectors = [
            'a.sa_text_lede',
            'a.sa_text_strong',
            '.sa_text a',
            '.cluster_text_headline a',
            '.cluster_text_lede a'
        ]

        for selector in selectors:
            elements = driver.find_elements(By.CSS_SELECTOR, selector)
            for element in elements:
                url = element.get_attribute('href')
                if (url and 'news.naver.com' in url and '/article/' in url
                    and '/comment/' not in url
                    and url not in article_links):
                    article_links.append(url)
                    if len(article_links) >= num_articles:
                        break
            if len(article_links) >= num_articles:
                break
        
        print(f'✓ {len(article_links)}개의 기사 링크 수집 완료')
    
    except Exception as e:
        print(f'✗ 기사 링크 수집 실패: {e}')
    
    return article_links[:num_articles]

In [9]:
def parse_article_detail(driver, article_url, category):
    driver.get(article_url)
    time.sleep(1.5)

    article_data = {
        'article_id': '',
        'title': '',
        'content': '',
        'url': article_url,
        'published_date': '',
        'source': '',
        'author': '',
        'category': category
    }

    try:
        match = re.search(r'article/(\d+)/(\d+)', article_url)
        if match:
            article_data['article_id'] = f'ART_{match.group(1)}_{match.group(2)}'
        else:
            article_data['article_id'] = f"ART_{datetime.now().strftime('%Y%m%d%H%M%S')}"
        
        title_selectors = [
            '#title_area span',
            '#ct .media_end_head_headline',
            '.media_end_head_headline',
            'h2#title_area',
            '.news_end_title'
        ]

        for selector in title_selectors:
            try:
                title_element = driver.find_element(By.CSS_SELECTOR, selector)
                if title_element.text.strip():
                    article_data['title'] = title_element.text.strip()
                    break
            except:
                continue
        
        content_selectors = [
            '#dic_area',
            'article#dic_area',
            '.go_trans._article_content',
            '._article_body_contents'
        ]

        for selector in content_selectors:
            try:
                content_element = driver.find_element(By.CSS_SELECTOR, selector)
                if content_element.text.strip():
                    article_data['content'] = content_element.text.strip()
                    break
            except:
                continue
        
        try:
            source_element = driver.find_element(By.CSS_SELECTOR, 'a.media_end_head_top_logo img')
            article_data['source'] = source_element.get_attribute('alt')
        except:
            try:
                source_element = driver.find_element(By.CSS_SELECTOR, '.media_end_head_top_logo_text')
                article_data['source'] = source_element.text.strip()
            except:
                pass
        
        try:
            date_element = driver.find_element(By.CSS_SELECTOR, 'span.media_end_head_info_datestamp_time, span[data-date-time]')
            date_text = date_element.get_attribute('data-date-time') or date_element.text
            article_data['published_date'] = date_text.strip()
        except:
            article_data['published_date'] = datetime.now().strftime('%Y-%m-%d %H:%M')
        
        try:
            author_element = driver.find_element(By.CSS_SELECTOR, 'em.media_end_head_journalist_name, span.byline_s')
            article_data['author'] = author_element.text.strip()
        except:
            pass
    
    except Exception as e:
        print(f' ✗ 파싱 오류: {e} ')
    
    return article_data

In [10]:
all_articles = []

for category_name, category_url in categories.items():
    print(f'\n{"="*60}')
    print(f"[{category_name}] 카테고리 수집 시작...")
    print(f"{'='*60}")

    article_links = get_article_links(driver, category_url, NUM_ARTICLES_PER_CATEGORY)

    for idx, article_url in enumerate(article_links, 1):
        print(f"  [{idx}/{len(article_links)}] {article_url}")
        article_data = parse_article_detail(driver, article_url, category_name)

        if article_data['title']:
            all_articles.append(article_data)
            print(f"  ✓ 수집 완료: {article_data['title'][:50]}...")
        else:
            print(f"  ✗ 수집 실패 - 제목을 찾을 수 없습니다.")
        
        time.sleep(0.5)

============================================================
[정치] 카테고리 수집 시작...
============================================================
✓ 10개의 기사 링크 수집 완료
  [1/10] https://n.news.naver.com/mnews/article/014/0005456806
  ✓ 수집 완료: '1억 수수 의혹' 강선우 "어떠한 돈도 받은 적 없다"...
  [2/10] https://n.news.naver.com/mnews/article/421/0008689788
  ✓ 수집 완료: 李대통령, 韓 대도약 이끌 5대 성장 전략 제시…"2026년은 대도약 원년"(종합)...
  [3/10] https://n.news.naver.com/mnews/article/052/0002294688
  ✓ 수집 완료: 청문회에서 '호통' 쿠팡 로저스...오늘도 '마이웨이'...
  [4/10] https://n.news.naver.com/mnews/article/366/0001133586
  ✓ 수집 완료: 文 만난 조국 “李정부 성공 위한 레드팀 역할 할 것”...
  [5/10] https://n.news.naver.com/mnews/article/001/0015823756
  ✓ 수집 완료: 李대통령, 현충원 참배…"대도약 원년 국민과 함께 열겠다"...
  [6/10] https://n.news.naver.com/mnews/article/008/0005299104
  ✓ 수집 완료: 김민석, 새해 인사 "내란 완전 청산, 민주주의 굳건히 하는 한 해 될 것"...
  [7/10] https://n.news.naver.com/mnews/article/055/0001320813
  ✓ 수집 완료: 김정은, 파병 군인 가족과 새해 공연…"평양·모스크바가 있다"...
  [8/10] https://n.news.naver.com/mnews/article/011/0004573653
  ✓ 수집 완료: [신년사]장동혁 "국민 삶 생각하면 '선거 승리' 따라올 것"...
  [9/10] https://n.news.naver.com/mnews/article/020/0003686138
  ✓ 수집 완료: 봉하마을 참배한 정청래 “김대중 노무현 문재인의 꿈 계승”...
  [10/10] https://n.news.naver.com/mnews/article/015/0005231492
  ✓ 수집 완료: 이혜훈 이어 유승민도?…"총리 제안 왔지만 답변 안했다"...

============================================================
[경제] 카테고리 수집 시작...
============================================================
✓ 10개의 기사 링크 수집 완료
  [1/10] https://n.news.naver.com/mnews/article/009/0005614975
  ✓ 수집 완료: 외식업 10곳 중 6곳 ‘노쇼’ 경험...1회당 손실액 44만원...
  [2/10] https://n.news.naver.com/mnews/article/011/0004573559
  ✓ 수집 완료: 환율 쇼크에 기름값 ‘역주행’…경유 10.8% 급등[Pick코노미]...
  [3/10] https://n.news.naver.com/mnews/article/469/0000906438
  ✓ 수집 완료: 하나은행, 새해 맞아 지역 군부대 방문… "군의 평생 금융파트너"...
  [4/10] https://n.news.naver.com/mnews/article/008/0005299169
  ✓ 수집 완료: 국내 20개 은행, '새도약기금'에 총 3600억 출연...
  [5/10] https://n.news.naver.com/mnews/article/008/0005299127
  ✓ 수집 완료: 박정원 두산 회장 "전사적 역량 모아 AI 전환 가속화해야"...
  [6/10] https://n.news.naver.com/mnews/article/277/0005700952
  ✓ 수집 완료: 2025년 수출 '역대 최대'…산업부 "2년 연속 7000억달러 달성할 것"...
  [7/10] https://n.news.naver.com/mnews/article/016/0002579629
  ✓ 수집 완료: [신년사] 김영훈 노동장관 “일하다 죽지 않는 나라, 2026년에 반드시 만들겠다”...
  [8/10] https://n.news.naver.com/mnews/article/020/0003686145
  ✓ 수집 완료: 올해 내연차를 전기차로 바꾸면 보조금 100만원 더 받는다...
  [9/10] https://n.news.naver.com/mnews/article/293/0000077183
  ✓ 수집 완료: [2026 아웃룩] AI 확산으로 '메모리반도체' 봄날 계속된다...
  [10/10] https://n.news.naver.com/mnews/article/050/0000100406
  ✓ 수집 완료: “노르웨이산도 국산도 비싸다” 고등어 가격 고공행진...

============================================================
[사회] 카테고리 수집 시작...
============================================================
✓ 10개의 기사 링크 수집 완료
  [1/10] https://n.news.naver.com/mnews/article/001/0015823238
  ✓ 수집 완료: 현직 법관 90% "법관 증원 필요"…과반수 주52시간 초과근무...
  [2/10] https://n.news.naver.com/mnews/article/469/0000906417
  ✓ 수집 완료: 현역 입대 싫어서… 하루 줄넘기 1000개하며 밥 굶은 20대男 유죄...
  [3/10] https://n.news.naver.com/mnews/article/001/0015823971
  ✓ 수집 완료: 부산지역 대학 정시 경쟁률 작년보다 상승…부산대 4.67 대 1...
  [4/10] https://n.news.naver.com/mnews/article/014/0005456794
  ✓ 수집 완료: '일타강사' 현우진 "수능 문제 '거래' 아냐" 반박...
  [5/10] https://n.news.naver.com/mnews/article/008/0005299191
  ✓ 수집 완료: 윤 전 대통령 부부 운명의 달 시작…내란·특검 관련 재판 줄줄이 선고...
  [6/10] https://n.news.naver.com/mnews/article/421/0008690493
  ✓ 수집 완료: "새해엔 적토마처럼 달리자"…전국 곳곳 해맞이 '인산인해'(종합2보)...
  [7/10] https://n.news.naver.com/mnews/article/003/0013687465
  ✓ 수집 완료: 마제촌·도마산·안마도…전남, 말 지명 216곳 '전국 최다'...
  [8/10] https://n.news.naver.com/mnews/article/374/0000483734
  ✓ 수집 완료: 올해 '기준 중위소득' 4인가구 649만원…인상률 역대 최고...
  [9/10] https://n.news.naver.com/mnews/article/001/0015824316
  ✓ 수집 완료: 정원오 "시민 불편 맞서고 삶의 변화 만들 것…도전할 시간"...
  [10/10] https://n.news.naver.com/mnews/article/008/0005299207
  ✓ 수집 완료: 횡단보도 건너던 어린이 2명 치고 도주…30대 오토바이 운전자 검거...

============================================================
[생활/문화] 카테고리 수집 시작...
============================================================
✓ 10개의 기사 링크 수집 완료
  [1/10] https://n.news.naver.com/mnews/article/023/0003950265
  ✓ 수집 완료: 새해 첫날 전국 꽁꽁… 해돋이는 잘 보여요...
  [2/10] https://n.news.naver.com/mnews/article/660/0000100256
  ✓ 수집 완료: 새해 첫날 전국 '강추위'...남부 지역에 눈...
  [3/10] https://n.news.naver.com/mnews/article/052/0002294938
  ✓ 수집 완료: 새해 첫날 강추위 계속...밤사이 서해안·제주도 눈 집중...
  [4/10] https://n.news.naver.com/mnews/article/009/0005614963
  ✓ 수집 완료: ‘톰과제리’ 성우 송도순 별세…향년 77세...
  [5/10] https://n.news.naver.com/mnews/article/056/0012096923
  ✓ 수집 완료: 내일도 한파 이어져…서해안과 제주에는 눈...
  [6/10] https://n.news.naver.com/mnews/article/030/0003385988
  ✓ 수집 완료: [미리보는 CES 2026]〈하〉모빌리티, 새로운 'AI 생태계'로 진화...
  [7/10] https://n.news.naver.com/mnews/article/346/0000102547
  ✓ 수집 완료: 구교환, “있으면 무조건 먹는다” 밝힌 디저트의 정체… 뭐지?...
  [8/10] https://n.news.naver.com/mnews/article/296/0000096205
  ✓ 수집 완료: 강력한 로마 검투사들은 우리가 예상한 ‘그것’ 먹은 게 아니었다...
  [9/10] https://n.news.naver.com/mnews/article/032/0003418861
  ✓ 수집 완료: 새해에도 잿빛 전망…우울한 분위기로 출발하는 ‘K-배터리’...
  [10/10] https://n.news.naver.com/mnews/article/052/0002294960
  ✓ 수집 완료: 새해 첫날, 내륙 맑지만 강추위...밤사이 서해안·제주도 강한 눈...

============================================================
[IT/과학] 카테고리 수집 시작...
============================================================
✓ 10개의 기사 링크 수집 완료
  [1/10] https://n.news.naver.com/mnews/article/001/0015823382
  ✓ 수집 완료: [신년사] 과기부총리 "K-AI 영토 확장·미래 전략기술 육성 박차"...
  [2/10] https://n.news.naver.com/mnews/article/008/0005299160
  ✓ 수집 완료: "AI 3강 도약"…올해 8.1조 규모 연구·개발 착수한다...
  [3/10] https://n.news.naver.com/mnews/article/009/0005614999
  ✓ 수집 완료: 해킹 여파에...KT, 위약금 면제 첫 날 가입자 1만명 빠져나가...
  [4/10] https://n.news.naver.com/mnews/article/001/0015823561
  ✓ 수집 완료: [미리보는 CES] ③ 가전 넘어 칩·부품 경쟁…AI시대 판세 읽는 무대...
  [5/10] https://n.news.naver.com/mnews/article/023/0003950359
  ✓ 수집 완료: 새해 최고 부자는 머스크 895조원... 테크 창업자가 상위권 휩쓸어...
  [6/10] https://n.news.naver.com/mnews/article/469/0000906465
  ✓ 수집 완료: 실감 나는 AI 세상 예고한 CES... 키워드, '공간컴퓨팅'과 '인터랙티브'...
  [7/10] https://n.news.naver.com/mnews/article/030/0003385980
  ✓ 수집 완료: AI 강국의 길…'한국형 필승 카드'로 연다...
  [8/10] https://n.news.naver.com/mnews/article/029/0003002501
  ✓ 수집 완료: 제약바이오 ‘오너 3·4세 경영’ 전면화…R&D·글로벌 전략 직접 챙긴다...
  [9/10] https://n.news.naver.com/mnews/article/029/0003002495
  ✓ 수집 완료: K-제약바이오, 성장 기록 쓴 한해…기술수출 확대에도 웃지 못한 이유는...
  [10/10] https://n.news.naver.com/mnews/article/018/0006193312
  ✓ 수집 완료: 해수 그린수소 새 길…서울대-HD한국조선해양, 고내구 촉매 개발...

============================================================
[세계] 카테고리 수집 시작...
============================================================
✓ 10개의 기사 링크 수집 완료
  [1/10] https://n.news.naver.com/mnews/article/366/0001133511
  ✓ 수집 완료: 美 국무부, 韓정보통신망법에 “중대 우려… 美 플랫폼 기업에 부정적”...
  [2/10] https://n.news.naver.com/mnews/article/056/0012096715
  ✓ 수집 완료: 미, 베네수엘라 ‘그림자 선단’ 등 제재…“마두로 압박 계속”...
  [3/10] https://n.news.naver.com/mnews/article/025/0003493522
  ✓ 수집 완료: "다카이치 대만 발언 타이밍 나빴다…중일 갈등 1년 지속될 듯"...
  [4/10] https://n.news.naver.com/mnews/article/023/0003950359
  ✓ 수집 완료: 새해 최고 부자는 머스크 895조원... 테크 창업자가 상위권 휩쓸어...
  [5/10] https://n.news.naver.com/mnews/article/001/0015823340
  ✓ 수집 완료: "AI 도입에 유럽 은행 일자리 5년내 20만개 위험"...
  [6/10] https://n.news.naver.com/mnews/article/448/0000580677
  ✓ 수집 완료: 트럼프 "시카고·LA·포틀랜드 軍 철수…범죄 늘면 재배치"...
  [7/10] https://n.news.naver.com/mnews/article/032/0003418544
  ✓ 수집 완료: 미 의회, 중국군 대만 포위 훈련에 “의도적 상황 악화 행위” 비판...
  [8/10] https://n.news.naver.com/mnews/article/052/0002294961
  ✓ 수집 완료: 뉴욕 타임스퀘어 볼 드롭 보며 백만 명 새해 맞이해...미국 건국 250주년 기념...
  [9/10] https://n.news.naver.com/mnews/article/015/0005231558
  ✓ 수집 완료: "S&P500, 7000선 안착…돈되는 AI株 담아야"...
  [10/10] https://n.news.naver.com/mnews/article/015/0005231557
  ✓ 수집 완료: 가치주·기술주 중심 랠리 지속…닛케이 연말 5만5000 뚫을 것...

In [11]:
df_articles = pd.DataFrame(all_articles)

In [12]:
df_articles

,article_id,title,content,url,published_date,source,author,category
0,ART_014_0005456806,"'1억 수수 의혹' 강선우 ""어떠한 돈도 받은 적 없다""",(출처=연합뉴스)\n\n[파이낸셜뉴스] 강선우 더불어민주당 의원이 2022년 지방선...,https://n.news.naver.com/mnews/article/014/000...,2026-01-01 10:25:11,파이낸셜뉴스,한승곤 기자,정치
1,ART_421_0008689788,"李대통령, 韓 대도약 이끌 5대 성장 전략 제시…""2026년은 대도약 원년""(종합)","[신년사] '지방·분배·안전·문화·평화' 5대 성장 천명\n""성장 패러다임 완전히 ...",https://n.news.naver.com/mnews/article/421/000...,2026-01-01 05:00:00,뉴스1,이기림 외 2명,정치
2,ART_052_0002294688,청문회에서 '호통' 쿠팡 로저스...오늘도 '마이웨이',[앵커]\n국회에서 이틀째 쿠팡 청문회가 이어지고 있습니다.\n\n어제 로저스 쿠팡...,https://n.news.naver.com/mnews/article/052/000...,2025-12-31 17:45:48,YTN,이승은 기자,정치
3,ART_366_0001133586,文 만난 조국 “李정부 성공 위한 레드팀 역할 할 것”,조국 조국혁신당 대표와 서왕진 원내대표를 비롯한 지도부가 1일 새해를 맞아 경남 양...,https://n.news.naver.com/mnews/article/366/000...,2026-01-01 15:12:07,조선비즈,이종현 기자,정치
4,ART_001_0015823756,"李대통령, 현충원 참배…""대도약 원년 국민과 함께 열겠다""","새해 일정 시작…참배 후 참모진·국무뮈원과 떡국 조찬\n\n\n이재명 대통령, 현충...",https://n.news.naver.com/mnews/article/001/001...,2026-01-01 08:45:53,연합뉴스,고동욱 기자,정치
5,ART_008_0005299104,"김민석, 새해 인사 ""내란 완전 청산, 민주주의 굳건히 하는 한 해 될 것""",[the300]\n김민석 국무총리가 지난해 12월 31일 오전 서울 종로구 정부서울...,https://n.news.naver.com/mnews/article/008/000...,2026-01-01 09:27:35,머니투데이,김지은 기자,정치
6,ART_055_0001320813,"김정은, 파병 군인 가족과 새해 공연…""평양·모스크바가 있다""",▲ 평양 5월1일 경기장에서 열린 신년 경축 행사에 참석한 김정은 북한 국무위원장\...,https://n.news.naver.com/mnews/article/055/000...,2026-01-01 09:26:22,SBS,김아영 기자,정치
7,ART_011_0004573653,"[신년사]장동혁 ""국민 삶 생각하면 '선거 승리' 따라올 것""","""더 낮은 자세로 국민 섬기는 정당 될 것""\n장동혁 국민의힘 대표가 새해 첫 날인...",https://n.news.naver.com/mnews/article/011/000...,2026-01-01 11:42:10,서울경제,이진석 기자,정치
8,ART_020_0003686138,봉하마을 참배한 정청래 “김대중 노무현 문재인의 꿈 계승”,정청래 더불어민주당 대표가 1일 오후 경남 김해 진영읍 봉하마을을 찾아 고 노무현 ...,https://n.news.naver.com/mnews/article/020/000...,2026-01-01 14:26:16,동아일보,송치훈 기자,정치
9,ART_015_0005231492,"이혜훈 이어 유승민도?…""총리 제안 왔지만 답변 안했다""",이재명 정부 '보수인사 기용설'에 직접 언급\n사진=연합뉴스\n\n이재명 정부 초대...,https://n.news.naver.com/mnews/article/015/000...,2026-01-01 10:57:12,한국경제,김봉구 기자,정치
10,ART_009_0005614975,외식업 10곳 중 6곳 ‘노쇼’ 경험...1회당 손실액 44만원,‘소상공인 노쇼 피해 실태조사’ 발표\n피해점포 3년간 평균 8.6회 노쇼 발생\n...,https://n.news.naver.com/mnews/article/009/000...,2026-01-01 13:59:07,매일경제,곽은산 기자,경제
11,ART_011_0004573559,환율 쇼크에 기름값 ‘역주행’…경유 10.8% 급등[Pick코노미],2025년 12월 석유류 6.1% ↑\n경유 10.8%·휘발유 5.7% 상승\n20...,https://n.news.naver.com/mnews/article/011/000...,2026-01-01 05:31:10,서울경제,배상윤 기자,경제
12,ART_469_0000906438,"하나은행, 새해 맞아 지역 군부대 방문… ""군의 평생 금융파트너""",이호성(왼쪽 여섯 번째) 하나은행장과 하나은행 임직원들이 1일 경기 파주시 소재 도...,https://n.news.naver.com/mnews/article/469/000...,2026-01-01 13:50:12,한국일보,전유진 기자,경제
13,ART_008_0005299169,"국내 20개 은행, '새도약기금'에 총 3600억 출연","[서울=뉴시스] 정병혁 기자 = 왼쪽 두번째부터 양혁승 새도약기금 대표이사, 여영현...",https://n.news.naver.com/mnews/article/008/000...,2026-01-01 12:00:00,머니투데이,이병권 기자,경제
14,ART_008_0005299127,"박정원 두산 회장 ""전사적 역량 모아 AI 전환 가속화해야""","박정원 두산그룹 회장./사진제공=두산\n박정원 두산그룹 회장이 ""전사적 역량을 모아...",https://n.news.naver.com/mnews/article/008/000...,2026-01-01 10:27:57,머니투데이,김도균 기자,경제
15,ART_277_0005700952,"2025년 수출 '역대 최대'…산업부 ""2년 연속 7000억달러 달성할 것""","산업부, 2025년 연간 및 12월 수출입 동향\n지난해 수출 7097억달러·무역흑...",https://n.news.naver.com/mnews/article/277/000...,2026-01-01 09:33:10,아시아경제,주상돈 기자,경제
16,ART_016_0002579629,"[신년사] 김영훈 노동장관 “일하다 죽지 않는 나라, 2026년에 반드시 만들겠다”",산재감독 2.4만→5만곳 확대…임금체불은 ‘절도’ 규정\n주 4.5일제 재정 지원·...,https://n.news.naver.com/mnews/article/016/000...,2026-01-01 00:01:13,헤럴드경제,김용훈 기자,경제
17,ART_020_0003686145,올해 내연차를 전기차로 바꾸면 보조금 100만원 더 받는다,서영태 기후에너지환경부 녹색전환정책관이 지난달 31일 세종시 정부세종청사에서 202...,https://n.news.naver.com/mnews/article/020/000...,2026-01-01 15:12:15,동아일보,최혜령 기자,경제
18,ART_293_0000077183,[2026 아웃룩] AI 확산으로 '메모리반도체' 봄날 계속된다,삼성전자가 지난 10월 서울 강남구 코엑스에서 열린 '반도체대전(SEDEX) 202...,https://n.news.naver.com/mnews/article/293/000...,2025-12-31 09:10:10,블로터,김수정 기자,경제
19,ART_050_0000100406,“노르웨이산도 국산도 비싸다” 고등어 가격 고공행진,고등어 가격이 가파르게 오르면서\n서울의 한 대형마트에서 장을 보는 시민들. 202...,https://n.news.naver.com/mnews/article/050/000...,2026-01-01 10:47:10,한경비즈니스,정유진 기자,경제
20,ART_001_0015823238,"현직 법관 90% ""법관 증원 필요""…과반수 주52시간 초과근무","""600명 전후 증원 필요""…91% ""소송사건 난도·복잡성 상승""\n\n\n법원\n...",https://n.news.naver.com/mnews/article/001/001...,2025-12-31 20:22:48,연합뉴스,이미령 기자,사회
21,ART_469_0000906417,현역 입대 싫어서… 하루 줄넘기 1000개하며 밥 굶은 20대男 유죄,"병역법 위반 징역 8개월에 집유 2년 선고\n""복무 회피 목적... 방법 주변에 권...",https://n.news.naver.com/mnews/article/469/000...,2026-01-01 10:17:08,한국일보,최동순 기자,사회
22,ART_001_0015823971,부산지역 대학 정시 경쟁률 작년보다 상승…부산대 4.67 대 1,"부경대 7.19 대 1, 한국해양대 6.73 대 1, 동의대 7.88 대 1\n\n...",https://n.news.naver.com/mnews/article/001/001...,2026-01-01 10:08:28,연합뉴스,조정호 기자,사회
23,ART_014_0005456794,"'일타강사' 현우진 ""수능 문제 '거래' 아냐"" 반박",수능 스타 강사 현우진/사진=현우진 인스타그램 캡처\n\n\n[파이낸셜뉴스] 수능 ...,https://n.news.naver.com/mnews/article/014/000...,2026-01-01 09:49:10,파이낸셜뉴스,한승곤 기자,사회
24,ART_008_0005299191,윤 전 대통령 부부 운명의 달 시작…내란·특검 관련 재판 줄줄이 선고,윤석열 전 대통령 /사진=뉴스1(사진공동취재단)\n윤석열 전 대통령 부부의 형사 재...,https://n.news.naver.com/mnews/article/008/000...,2026-01-01 14:10:05,머니투데이,이혜수 기자,사회
25,ART_421_0008690493,"""새해엔 적토마처럼 달리자""…전국 곳곳 해맞이 '인산인해'(종합2보)","포항 영일대·임실·천안까지 병오년 첫 일출 풍경\n""올해는 부디 행복하길""…취업·이...",https://n.news.naver.com/mnews/article/421/000...,2026-01-01 11:29:45,뉴스1,윤왕근 외 8명,사회
26,ART_003_0013687465,"마제촌·도마산·안마도…전남, 말 지명 216곳 '전국 최다'",전국 820여곳 중…마을·섬·산 등 순 많아\n[무안=뉴시스] 영광 안마도. (사진...,https://n.news.naver.com/mnews/article/003/001...,2026-01-01 11:12:58,뉴시스,구용희 기자,사회
27,ART_374_0000483734,올해 '기준 중위소득' 4인가구 649만원…인상률 역대 최고,[연합뉴스 자료사진]\n\n정부가 기초생활보장제도 등 각종 복지사업의 잣대가 되는 ...,https://n.news.naver.com/mnews/article/374/000...,2026-01-01 13:37:12,SBS Biz,박규준 기자,사회
28,ART_001_0015824316,"정원오 ""시민 불편 맞서고 삶의 변화 만들 것…도전할 시간""","시장출마 거론 속 새해 글…""계엄정국 시민 힘이 방향 만들어, 도전 이어가겠다""\n...",https://n.news.naver.com/mnews/article/001/001...,2026-01-01 14:10:24,연합뉴스,정수연 기자,사회
29,ART_008_0005299207,횡단보도 건너던 어린이 2명 치고 도주…30대 오토바이 운전자 검거,횡단보도에서 어린이들을 치고 도주한 오토바이 운전자가 도주했다가 붙잡혔다. 위 사진...,https://n.news.naver.com/mnews/article/008/000...,2026-01-01 15:15:44,머니투데이,윤혜주 기자,사회
30,ART_023_0003950265,새해 첫날 전국 꽁꽁… 해돋이는 잘 보여요,"서울, 오늘 체감 영하 14도\n영하 16도의 한파 속에서 새해를 여는 첫 태양은 ...",https://n.news.naver.com/mnews/article/023/000...,2026-01-01 00:45:17,조선일보,박상현 기자,생활/문화
31,ART_660_0000100256,새해 첫날 전국 '강추위'...남부 지역에 눈,▲ 2026 병오년 첫해를 보려는 해맞이객들로 가득찬 일출 명소 \n\n새해 첫날인...,https://n.news.naver.com/mnews/article/660/000...,2026-01-01 06:23:10,kbc광주방송,임경섭 기자,생활/문화
32,ART_052_0002294938,새해 첫날 강추위 계속...밤사이 서해안·제주도 눈 집중,"[앵커]\n새해 첫날인 오늘, 한낮에도 강추위가 계속되고 있습니다.\n\n밤사이 서...",https://n.news.naver.com/mnews/article/052/000...,2026-01-01 14:16:26,YTN,김시아(gbs06253@ytn.co.kr),생활/문화
33,ART_009_0005614963,‘톰과제리’ 성우 송도순 별세…향년 77세,‘함께 가는 저녁길’ 17년간 진행\n\n\n교통방송(TBS)에서 성우 배한성씨와 ...,https://n.news.naver.com/mnews/article/009/000...,2026-01-01 13:11:10,매일경제,정유정 기자,생활/문화
34,ART_056_0012096923,내일도 한파 이어져…서해안과 제주에는 눈,새해 첫날인 오늘 매서운 한파 속에 제주에는 눈이 오겠습니다.\n\n밤부터는 충남 ...,https://n.news.naver.com/mnews/article/056/001...,2026-01-01 14:00:11,KBS,이정훈 기자,생활/문화
35,ART_030_0003385988,"[미리보는 CES 2026]〈하〉모빌리티, 새로운 'AI 생태계'로 진화",아우모비오가 CES 2026에 선보일 운전자 주행 보조 및 자율주행 플랫폼 젤브(X...,https://n.news.naver.com/mnews/article/030/000...,2026-01-01 16:01:38,전자신문,정치연 기자,생활/문화
36,ART_346_0000102547,"구교환, “있으면 무조건 먹는다” 밝힌 디저트의 정체… 뭐지?",[스타의 건강]\n배우 구교환이 즐겨먹는 식혜는 우리나라 전통 음료로 장 건강을 개...,https://n.news.naver.com/mnews/article/346/000...,2026-01-01 16:01:11,헬스조선,최소라 기자,생활/문화
37,ART_296_0000096205,강력한 로마 검투사들은 우리가 예상한 ‘그것’ 먹은 게 아니었다,[송무호의 비건뉴스] 109. 단백질 보충제 ⑨\n로마 검투사들은 단순한 전사라기보...,https://n.news.naver.com/mnews/article/296/000...,2026-01-01 16:00:09,코메디닷컴,송무호 동의의료원 의무원장 mhsong21@hanmail.net,생활/문화
38,ART_032_0003418861,새해에도 잿빛 전망…우울한 분위기로 출발하는 ‘K-배터리’,"올해 1분기 중으로 포드와 공동운영 체제를 접고, 독자 운영에 들어가는 SK온의 ‘...",https://n.news.naver.com/mnews/article/032/000...,2026-01-01 15:57:02,경향신문,권재현 기자,생활/문화
39,ART_052_0002294960,"새해 첫날, 내륙 맑지만 강추위...밤사이 서해안·제주도 강한 눈","[앵커]\n새해 첫날인 오늘, 종일 강추위가 기승을 부리고 있습니다.\n\n추위 속...",https://n.news.naver.com/mnews/article/052/000...,2026-01-01 15:56:27,YTN,김시아(gbs06253@ytn.co.kr),생활/문화
40,ART_001_0015823382,"[신년사] 과기부총리 ""K-AI 영토 확장·미래 전략기술 육성 박차""","""해킹과 전면전 추진…대도약의 한 해, 변화 선두에 설 것""\n\n\n과학기술관계장...",https://n.news.naver.com/mnews/article/001/001...,2026-01-01 00:00:22,연합뉴스,조성미 기자,IT/과학
41,ART_008_0005299160,"""AI 3강 도약""…올해 8.1조 규모 연구·개발 착수한다",과기정통부 2026년도 연구개발 종합시행계획\n과학기술정보통신부 MI\n\n과학기술...,https://n.news.naver.com/mnews/article/008/000...,2026-01-01 12:00:00,머니투데이,박건희 기자,IT/과학
42,ART_009_0005614999,"해킹 여파에...KT, 위약금 면제 첫 날 가입자 1만명 빠져나가",KT가 해킹 사태와 관련한 책임 조치로 2주간 위약금을 면제하고 데이터 추가 제공 ...,https://n.news.naver.com/mnews/article/009/000...,2026-01-01 15:03:09,매일경제,고민서 기자,IT/과학
43,ART_001_0015823561,[미리보는 CES] ③ 가전 넘어 칩·부품 경쟁…AI시대 판세 읽는 무대,"삼성·SK, AI 반도체 전시…엔비디아·AMD 등 빅테크도 출격\n부품·디스플레이 ...",https://n.news.naver.com/mnews/article/001/001...,2026-01-01 06:00:06,연합뉴스,한지은 기자,IT/과학
44,ART_023_0003950359,새해 최고 부자는 머스크 895조원... 테크 창업자가 상위권 휩쓸어,/그래픽=양진경\n\n2026년 첫날 세계 최고 부자 500명의 재산은 11조822...,https://n.news.naver.com/mnews/article/023/000...,2026-01-01 16:08:15,조선일보,박지민 기자 bgm@chosun.com,IT/과학
45,ART_469_0000906465,"실감 나는 AI 세상 예고한 CES... 키워드, '공간컴퓨팅'과 '인터랙티브'","LG전자, LLM 탑재 초경량 노트북 첫선\n삼성전자 '생활 공간 AI' 비전 공개...",https://n.news.naver.com/mnews/article/469/000...,2026-01-01 16:07:08,한국일보,김진욱 기자,IT/과학
46,ART_030_0003385980,AI 강국의 길…'한국형 필승 카드'로 연다,"붉은 말의 해 병오년(丙午年), 거침없는 도약과 활력을 상징하는 기운 속에서 대한민...",https://n.news.naver.com/mnews/article/030/000...,2026-01-01 16:01:13,전자신문,정현정 기자,IT/과학
47,ART_029_0003002501,제약바이오 ‘오너 3·4세 경영’ 전면화…R&D·글로벌 전략 직접 챙긴다,윤웅섭 일동제약 신임 회장. 일동제약 제공\n\n\n국내 제약·바이오 업계에서 오너...,https://n.news.naver.com/mnews/article/029/000...,2026-01-01 15:58:11,디지털타임스,이미선 기자,IT/과학
48,ART_029_0003002495,"K-제약바이오, 성장 기록 쓴 한해…기술수출 확대에도 웃지 못한 이유는",국내 제약·바이오 기업들이 해외 수출과 기술이전 계약 증가에 힘입어 2025년 역대...,https://n.news.naver.com/mnews/article/029/000...,2026-01-01 15:28:18,디지털타임스,강민성 기자,IT/과학
49,ART_018_0006193312,"해수 그린수소 새 길…서울대-HD한국조선해양, 고내구 촉매 개발","바닷물로 그린수소 ‘직접 생산’ 한걸음\n서울대 한정우 교수팀, HD한국조선해양\n...",https://n.news.naver.com/mnews/article/018/000...,2026-01-01 15:22:16,이데일리,김현아 기자,IT/과학
50,ART_366_0001133511,"美 국무부, 韓정보통신망법에 “중대 우려… 美 플랫폼 기업에 부정적”",미국 트럼프 행정부가 한국 국회가 통과시킨 정보통신망법 개정안에 대해 공식적으로 우...,https://n.news.naver.com/mnews/article/366/000...,2026-01-01 07:20:09,조선비즈,김송이 기자,세계
51,ART_056_0012096715,"미, 베네수엘라 ‘그림자 선단’ 등 제재…“마두로 압박 계속”",미국 도널드 트럼프 행정부가 베네수엘라 석유 부문에서 사업을 하는 회사 4곳과 유조...,https://n.news.naver.com/mnews/article/056/001...,2026-01-01 05:52:26,KBS,황현택 기자,세계
52,ART_025_0003493522,"""다카이치 대만 발언 타이밍 나빴다…중일 갈등 1년 지속될 듯""",다카이치 사나에(高市早苗) 일본 총리의 ‘대만 유사시 개입’ 시사 발언이 나온 지 ...,https://n.news.naver.com/mnews/article/025/000...,2025-12-31 05:00:05,중앙일보,도쿄=오누키 도모코 특파원 onuki.tomoko@joongang.co.kr,세계
53,ART_023_0003950359,새해 최고 부자는 머스크 895조원... 테크 창업자가 상위권 휩쓸어,/그래픽=양진경\n\n2026년 첫날 세계 최고 부자 500명의 재산은 11조822...,https://n.news.naver.com/mnews/article/023/000...,2026-01-01 16:08:15,조선일보,박지민 기자 bgm@chosun.com,세계
54,ART_001_0015823340,"""AI 도입에 유럽 은행 일자리 5년내 20만개 위험""",AI\n[로이터 연합뉴스 자료사진. 재판매 및 DB 금지]\n\n\n(런던=연합뉴스...,https://n.news.naver.com/mnews/article/001/001...,2025-12-31 22:36:15,연합뉴스,김지연 기자,세계
55,ART_448_0000580677,"트럼프 ""시카고·LA·포틀랜드 軍 철수…범죄 늘면 재배치""",도널드 트럼프 미국 대통령 /Reuters=연합뉴스\n도널드 트럼프 미국 대통령이 ...,https://n.news.naver.com/mnews/article/448/000...,2026-01-01 09:44:13,TV조선,지정용 기자,세계
56,ART_032_0003418544,"미 의회, 중국군 대만 포위 훈련에 “의도적 상황 악화 행위” 비판",29일 대만 포위 훈련인 정의의 사명 2025 훈련을 보도하는 CCTV 화면.\n\...,https://n.news.naver.com/mnews/article/032/000...,2025-12-31 07:40:00,경향신문,박은경 기자,세계
57,ART_052_0002294961,뉴욕 타임스퀘어 볼 드롭 보며 백만 명 새해 맞이해...미국 건국 250주년 기념,[앵커]\n뉴욕 타임스퀘어에서는 미국 건국 250주년을 기념하는 '성조기 크리스털 ...,https://n.news.naver.com/mnews/article/052/000...,2026-01-01 15:58:30,YTN,이승윤 기자,세계
58,ART_015_0005231558,"""S&P500, 7000선 안착…돈되는 AI株 담아야""",미국 증시 전망\n\nAI 거품론 vs 대세론 시험대\n기업 영업이익률 고점 경신 ...,https://n.news.naver.com/mnews/article/015/000...,2026-01-01 16:13:14,한국경제,박신영 기자,세계
59,ART_015_0005231557,가치주·기술주 중심 랠리 지속…닛케이 연말 5만5000 뚫을 것,"일본 증시 전망\n지난해 일본 닛케이지수가 사상 처음으로 50,000을 돌파했다. ...",https://n.news.naver.com/mnews/article/015/000...,2026-01-01 16:12:19,한국경제,김일규 기자,세계

In [13]:
output_filename = f"Articles_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
df_articles.to_excel(output_filename, index=False, engine='openpyxl')

In [14]:
driver.quit()

In [15]:
df = pd.read_excel('Articles_20260101_164317.xlsx')
df.head()

,article_id,title,content,url,published_date,source,author,category
0,ART_014_0005456806,"'1억 수수 의혹' 강선우 ""어떠한 돈도 받은 적 없다""",(출처=연합뉴스)\n\n[파이낸셜뉴스] 강선우 더불어민주당 의원이 2022년 지방선...,https://n.news.naver.com/mnews/article/014/000...,2026-01-01 10:25:11,파이낸셜뉴스,한승곤 기자,정치
1,ART_421_0008689788,"李대통령, 韓 대도약 이끌 5대 성장 전략 제시…""2026년은 대도약 원년""(종합)","[신년사] '지방·분배·안전·문화·평화' 5대 성장 천명\n""성장 패러다임 완전히 ...",https://n.news.naver.com/mnews/article/421/000...,2026-01-01 05:00:00,뉴스1,이기림 외 2명,정치
2,ART_052_0002294688,청문회에서 '호통' 쿠팡 로저스...오늘도 '마이웨이',[앵커]\n국회에서 이틀째 쿠팡 청문회가 이어지고 있습니다.\n\n어제 로저스 쿠팡...,https://n.news.naver.com/mnews/article/052/000...,2025-12-31 17:45:48,YTN,이승은 기자,정치
3,ART_366_0001133586,文 만난 조국 “李정부 성공 위한 레드팀 역할 할 것”,조국 조국혁신당 대표와 서왕진 원내대표를 비롯한 지도부가 1일 새해를 맞아 경남 양...,https://n.news.naver.com/mnews/article/366/000...,2026-01-01 15:12:07,조선비즈,이종현 기자,정치
4,ART_001_0015823756,"李대통령, 현충원 참배…""대도약 원년 국민과 함께 열겠다""","새해 일정 시작…참배 후 참모진·국무뮈원과 떡국 조찬\n\n\n이재명 대통령, 현충...",https://n.news.naver.com/mnews/article/001/001...,2026-01-01 08:45:53,연합뉴스,고동욱 기자,정치

In [21]:
import neo4j
import os

import dotenv
dotenv.load_dotenv()

URI = os.environ.get('NEO4J_URI')
neo4j_user = os.environ.get('NEO4J_USERNAME')
neo4j_password = os.environ.get('NEO4J_PASSWORD')
AUTH = ('neo4j', os.getenv('NEO4J_PASSWORD', 'password'))

driver = neo4j.GraphDatabase.driver(URI, auth=AUTH)

In [22]:
def chunk_text(text, chunk_size=500, overlap=50):
    if pd.isna(text) or text == '':
        return []
    
    text = str(text)
    chunks = []

    for i in range(0, len(text), chunk_size - overlap):
        chunk = text[i:i + chunk_size]
        if chunk.strip():
            chunks.append(chunk.strip())
    
    return chunks

In [24]:
def clear_database(tx):
    tx.run('MATCH (n) DETACH DELETE n')

def create_constraints(tx):
    constraints = [
        'CREATE CONSTRAINT IF NOT EXISTS FOR (a: Article) REQUIRE a.article_id IS UNIQUE',
        'CREATE CONSTRAINT IF NOT EXISTS FOR (c: Content) REQUIRE c.content_id IS UNIQUE',
        'CREATE CONSTRAINT IF NOT EXISTS FOR (m: Media) REQUIRE m.name IS UNIQUE',
        'CREATE CONSTRAINT IF NOT EXISTS FOR (cat: Category) REQUIRE cat.name IS UNIQUE'
    ]

    for constraint in constraints:
        try:
            tx.run(constraint)
        except Exception as e:
            print(f"제약조건 생성 중 오류: {e}")

with driver.session() as session:
    session.execute_write(clear_database)
    session.execute_write(create_constraints)

In [25]:
def create_article_node(tx, article_data):
    query = '''
    MERGE (a: Article {article_id: $article_id})
    SET a.title = $title,
        a.url = $url,
        a.published_date = $published_date
    RETURN a
    '''
    tx.run(query,
           article_id=article_data['article_id'],
           title=article_data['title'],
           url=article_data['url'],
           published_date=article_data['published_date'])

def create_content_nodes(tx, article_id, content_chunks, article_data):
    for i, chunk in enumerate(content_chunks):
        content_id = f"{article_id}_chunk_{i}"

        query = '''
        MERGE (c:Content {content_id: $content_id})
        SET c.chunk = $chunk,
            c.article_id = $article_id,
            c.title = $title,
            c.url = $url,
            c.published_date = $published_date,
            c.chunk_index = $chunk_index
        '''
        tx.run(query,
               content_id=content_id,
               chunk=chunk,
               article_id=article_id,
               title=article_data['title'],
               url=article_data['url'],
               published_date=article_data['published_date'],
               chunk_index=i)
        
        relationship_query = '''
        MATCH (a:Article {article_id: $article_id})
        MATCH (c:Content {content_id: $content_id})
        MERGE (a)-[:HAS_CHUNK]->(c)
        '''
        tx.run(relationship_query,
               article_id=article_id,
               content_id=content_id)

def create_media_node_and_relationship(tx, article_id, source):
    if pd.isna(source) or source == '':
        return

    media_query = '''
    MERGE (m:Media {name: $source})
    RETURN m
    '''
    tx.run(media_query, source=source)

    relationship_query = '''
    MATCH (a:Article {article_id: $article_id})
    MATCH (m:Media {name: $source})
    MERGE (m)-[:PUBLISHED]->(a)
    '''
    tx.run(relationship_query,
           article_id=article_id,
           source=source)
    
def create_category_node_and_relationship(tx, article_id, category):
    if pd.isna(category) or category == '':
        return
    
    category_query = '''
    MERGE (cat:Category {name: $category})
    RETURN cat
    '''
    tx.run(category_query, category=category)

    relationship_query = '''
    MATCH (a:Article {article_id: $article_id})
    MATCH (cat:Category {name: $category})
    MERGE (a)-[:BELONGS_TO]->(cat)
    '''
    tx.run(relationship_query,
           article_id=article_id,
           category=category)

In [26]:
def build_graph_from_dataframe(df, chunk_size=500, overlap=50):
    with driver.session() as session:
        for idx, row in df.iterrows():
            try:
                article_id = row.get('article_id', '')

                article_data = {
                    'article_id': article_id,
                    'title': row.get('title', ''),
                    'url': row.get('url', ''),
                    'published_date': str(row.get('published_date', ''))
                }

                session.execute_write(create_article_node, article_data)

                if 'content' in row and pd.notna(row['content']) and row['content'] != '':
                    content_chunks = chunk_text(row['content'], chunk_size, overlap)
                    if content_chunks:
                        session.execute_write(create_content_nodes, article_id, content_chunks, article_data)
                
                if 'source' in row:
                    session.execute_write(create_media_node_and_relationship, article_id, row['source'])

                if 'category' in row:
                    session.execute_write(create_category_node_and_relationship, article_id, row['category'])
                
                if (idx + 1) % 10 == 0:
                    print(f"진행률: {idx + 1}/{len(df)} ({((idx + 1)/len(df)*100):.1f}%)")
            
            except Exception as e:
                print(f"기사 {idx} 처리 중 오류 발생: {e}")
                continue

In [27]:
with driver.session() as session:
    print('데이터베이스 초기화 중...')
    session.execute_write(clear_database)
    session.execute_write(create_constraints)

build_graph_from_dataframe(df, chunk_size=500, overlap=50)

데이터베이스 초기화 중...
진행률: 10/60 (16.7%)
진행률: 20/60 (33.3%)
진행률: 30/60 (50.0%)
진행률: 40/60 (66.7%)
진행률: 50/60 (83.3%)
진행률: 60/60 (100.0%)

In [2]:
import os
import neo4j
import dotenv
from neo4j_graphrag.llm import OpenAILLM
from neo4j_graphrag.retrievers import VectorRetriever, VectorCypherRetriever, Text2CypherRetriever, ToolsRetriever
from neo4j_graphrag.embeddings.openai import OpenAIEmbeddings
from neo4j_graphrag.indexes import create_vector_index
from neo4j_graphrag.generation import RagTemplate, GraphRAG

dotenv.load_dotenv()

URI = os.getenv('NEO4J_URI')
AUTH = ('neo4j', os.getenv('NEO4J_PASSWORD'))
driver = neo4j.GraphDatabase.driver(URI, auth=AUTH)

llm = OpenAILLM(
    model_name='gpt-4o',
    model_params={'temperature': 0}
)
embedder = OpenAIEmbeddings(model='text-embedding-3-small')

In [3]:
with driver.session() as session:
    result = session.run('MATCH (c:Content) WHERE c.embedding IS NULL RETURN elementId(c) AS id, c.chunk AS text')
    records = result.data()

    for record in records:
        node_id = record['id']
        text = record['text']
        vector = embedder.embed_query(text)

        session.run('''
        MATCH (c) WHERE elementId(c) = $id
        SET c.embedding = $embedding
        ''', {'id': node_id, 'embedding': vector})

In [4]:
INDEX_NAME = 'content_vector_index'
DIMENSION = 1536

create_vector_index(
    driver,
    INDEX_NAME,
    label='Content',
    embedding_property='embedding',
    dimensions=DIMENSION,
    similarity_fn='cosine',
)

In [5]:
vector_retriever = VectorRetriever(
    driver=driver,
    index_name=INDEX_NAME,
    embedder = embedder
)

In [6]:
results = vector_retriever.search(query_text='트럼프 대통령 정책', top_k=3)

print(f"검색 결과 수: {len(results.items)}")
for i, item in enumerate(results.items):
    print(f"\n결과 {i+1}:")
    print(f"Content: {item.content[:200]}...")
    if item.metadata:
        print(f"Metadata: {item.metadata}")

검색 결과 수: 3

결과 1:
Content: {'embedding': None, 'article_id': 'ART_448_0000580677', 'chunk_index': 0, 'content_id': 'ART_448_0000580677_chunk_0', 'chunk': '도널드 트럼프 미국 대통령 /Reuters=연합뉴스\n도널드 트럼프 미국 대통령이 31일(현지시간) 대도시에 범죄 척결을 위해 배...
Metadata: {'score': 0.6993929147720337, 'nodeLabels': ['Content'], 'id': '4:099022cf-34ca-42f9-9923-7a6ccafea874:284'}

결과 2:
Content: {'embedding': None, 'article_id': 'ART_056_0012096715', 'chunk_index': 1, 'content_id': 'ART_056_0012096715_chunk_1', 'chunk': '제재 위험에 계속 직면해있다는 것을 추가로 시사한다"고 덧붙였습니다.\n\n스콧 베선트 재무장관은 "불법적인 마두로 정권이 미국에...
Metadata: {'score': 0.6933881044387817, 'nodeLabels': ['Content'], 'id': '4:099022cf-34ca-42f9-9923-7a6ccafea874:267'}

결과 3:
Content: {'embedding': None, 'article_id': 'ART_366_0001133511', 'chunk_index': 0, 'content_id': 'ART_366_0001133511_chunk_0', 'chunk': '미국 트럼프 행정부가 한국 국회가 통과시킨 정보통신망법 개정안에 대해 공식적으로 우려를 나타냈다.\n\n도널드 트럼프 미국 대통령...
Metadata: {'score': 0.6913937330245972, 'nodeLabels': ['Content'], 'id': '4:099022cf-34ca-42f9-9923-7a6ccafea874:261'}

c:\Users\Jo\AppData\Local\Programs\Python311\Lib\site-packages\neo4j_graphrag\retrievers\vector.py:201: DeprecationWarning: The default returned 'id' field in the search results will be removed. Please switch to using 'elementId' instead.
  search_query, search_params = get_search_query(

In [7]:
results = vector_retriever.search(query_text='북한', top_k=3)

print(f"검색 결과 수: {len(results.items)}")
for i, item in enumerate(results.items):
    print(f"\n결과 {i+1}:")
    print(f"Content: {item.content[:200]}...")
    if item.metadata:
        print(f"Metadata: {item.metadata}")

검색 결과 수: 3

결과 1:
Content: {'embedding': None, 'article_id': 'ART_030_0003385980', 'chunk_index': 0, 'content_id': 'ART_030_0003385980_chunk_0', 'chunk': "붉은 말의 해 병오년(丙午年), 거침없는 도약과 활력을 상징하는 기운 속에서 대한민국 반도체 산업이 새로운 출발선에 섰다. 경기도...
Metadata: {'score': 0.640516996383667, 'nodeLabels': ['Content'], 'id': '4:099022cf-34ca-42f9-9923-7a6ccafea874:236'}

결과 2:
Content: {'embedding': None, 'article_id': 'ART_025_0003493522', 'chunk_index': 6, 'content_id': 'ART_025_0003493522_chunk_6', 'chunk': '한국 등 주변국에선 군사력 증강을 위한 것이라며 우려한다.\nA : 안보 문서 개정이나 방위비 증액 등은 일본이 아시아에서 더 많...
Metadata: {'score': 0.6204962730407715, 'nodeLabels': ['Content'], 'id': '4:099022cf-34ca-42f9-9923-7a6ccafea874:275'}

결과 3:
Content: {'embedding': None, 'article_id': 'ART_032_0003418544', 'chunk_index': 1, 'content_id': 'ART_032_0003418544_chunk_1', 'chunk': '협력할 것”이라고 강조했다.\n\n앞서 중국 인민해방군 동부전구는 29~30일(현지시간) 육·해·공군과 로켓군 병력을 동원해 대만...
Metadata: {'score': 0.617620050907135, 'nodeLabels': ['Content'], 'id': '4:099022cf-34ca-42f9-9923-7a6ccafea874:289'}

In [8]:
retrieval_query = '''
MATCH (content:Content)<-[:HAS_CHUNK]-(article:Article)
OPTIONAL MATCH (article)-[:BELONGS_TO]->(category:Category)<-[:BELONGS_TO]-(related_article:Article)
WHERE article <> related_article

RETURN
    content.content_id AS content_id,
    content.chunk AS chunk,
    content.title AS content_title,
    article.article_id AS article_id,
    article.title AS article_title,
    article.url AS article_url,
    article.published_date AS article_date,
    category.name AS category_name,
    collect(DISTINCT {
        article_id: related_article.article_id,
        title: related_article.title,
        url: related_article.url,
        published_date: related_article.published_date
    }) AS related_articles

ORDER BY article.published_date DESC
LIMIT 1
'''

In [9]:
vector_cypher_retriever = VectorCypherRetriever(
    driver=driver,
    index_name=INDEX_NAME,
    retrieval_query=retrieval_query,
    embedder=embedder
)

In [10]:
results = vector_cypher_retriever.search(query_text='삼성전자')

print(f"검색 결과 수: {len(results.items)}")
for i, item in enumerate(results.items):
    print(f"\n결과 {i+1}:")
    print(f"Content: {item.content[:200]}...")
    print(item.content)

c:\Users\Jo\AppData\Local\Programs\Python311\Lib\site-packages\neo4j_graphrag\retrievers\vector.py:368: DeprecationWarning: The default returned 'id' field in the search results will be removed. Please switch to using 'elementId' instead.
  search_query, search_params = get_search_query(

검색 결과 수: 1

결과 1:
Content: <Record content_id='ART_015_0005231558_chunk_0' chunk="미국 증시 전망\n\nAI 거품론 vs 대세론 시험대\n기업 영업이익률 고점 경신 등\n'상승 랠리' 올해도 이어질 듯\n\n데이터센터·전력 수요 폭증에\n에너지인프라·유틸리티株 유망\n\n뜨거웠던 비만약 열풍 이어져\n헬스케어·바이오 등 혁신 기업\n'제2 ...
<Record content_id='ART_015_0005231558_chunk_0' chunk="미국 증시 전망\n\nAI 거품론 vs 대세론 시험대\n기업 영업이익률 고점 경신 등\n'상승 랠리' 올해도 이어질 듯\n\n데이터센터·전력 수요 폭증에\n에너지인프라·유틸리티株 유망\n\n뜨거웠던 비만약 열풍 이어져\n헬스케어·바이오 등 혁신 기업\n'제2 엔비디아' 될 가능성 커\n올해 미국 증시는 지난 2년간 기술주 열풍을 이끈 빅테크에 냉혹한 시험대가 될 것으로 전망된다. 이들 기업이 인공지능(AI) 부문에서 가시적 이익을 낼 수 있어야 주가 거품 논란에서 벗어나기 때문이다. 월가에선 작년보다 올해 미국의 기준금리 인하 속도가 둔화해 부채가 적고 현금 흐름이 좋은 기업에 투자자 시선이 쏠릴 것이란 예상이 나온다.\n\nAI 수익화의 원년\n골드만삭스는 최근 보고서를 통해 2026년 S&P500지수가 7000 선에 안착할 것이라는 낙관론을 내놨다. 그 근거는 AI 인프라 투자 결과물이 기업 주당순이익(EPS)으로 본격 전환되는 ‘수확의 시기’가 도래한다는 점이다.\n\n사비타 수브라마니안 뱅크오브아메리카(B" content_title='"S&P500, 7000선 안착…돈되는 AI株 담아야"' article_id='ART_015_0005231558' article_title='"S&P500, 7000선 안착…돈되는 AI株 담아야"' article_url='https://n.news.naver.com/mnews/article/015/0005231558' article_date='2026-01-01 16:13:14' category_name='세계' related_articles=[{'article_id': 'ART_023_0003950359', 'title': '새해 최고 부자는 머스크 895조원... 테크 창업자가 상위권 휩쓸어', 'published_date': '2026-01-01 16:08:15', 'url': 'https://n.news.naver.com/mnews/article/023/0003950359'}, {'article_id': 'ART_366_0001133511', 'title': '美 국무부, 韓정보통신망법에 “중대 우려… 美 플랫폼 기업에 부정적”', 'published_date': '2026-01-01 07:20:09', 'url': 'https://n.news.naver.com/mnews/article/366/0001133511'}, {'article_id': 'ART_056_0012096715', 'title': '미, 베네수엘라 ‘그림자 선단’ 등 제재…“마두로 압박 계속”', 'published_date': '2026-01-01 05:52:26', 'url': 'https://n.news.naver.com/mnews/article/056/0012096715'}, {'article_id': 'ART_025_0003493522', 'title': '"다카이치 대만 발언 타이밍 나빴다…중일 갈등 1년 지속될 듯"', 'published_date': '2025-12-31 05:00:05', 'url': 'https://n.news.naver.com/mnews/article/025/0003493522'}, {'article_id': 'ART_001_0015823340', 'title': '"AI 도입에 유럽 은행 일자리 5년내 20만개 위험"', 'published_date': '2025-12-31 22:36:15', 'url': 'https://n.news.naver.com/mnews/article/001/0015823340'}, {'article_id': 'ART_448_0000580677', 'title': '트럼프 "시카고·LA·포틀랜드 軍 철수…범죄 늘면 재배치"', 'published_date': '2026-01-01 09:44:13', 'url': 'https://n.news.naver.com/mnews/article/448/0000580677'}, {'article_id': 'ART_032_0003418544', 'title': '미 의회, 중국군 대만 포위 훈련에 “의도적 상황 악화 행위” 비판', 'published_date': '2025-12-31 07:40:00', 'url': 'https://n.news.naver.com/mnews/article/032/0003418544'}, {'article_id': 'ART_052_0002294961', 'title': '뉴욕 타임스퀘어 볼 드롭 보며 백만 명 새해 맞이해...미국 건국 250주년 기념', 'published_date': '2026-01-01 15:58:30', 'url': 'https://n.news.naver.com/mnews/article/052/0002294961'}, {'article_id': 'ART_015_0005231557', 'title': '가치주·기술주 중심 랠리 지속…닛케이 연말 5만5000 뚫을 것', 'published_date': '2026-01-01 16:12:19', 'url': 'https://n.news.naver.com/mnews/article/015/0005231557'}]>

In [11]:
import re
import json
import ast

def extract_field(text, name):
    pattern = rf"{name}\s*=\s*(?P<val>'[^']*'|\"[^\"]*\"|'''(?:.|\n)*?'''|\"\"\"(?:.|\n)*?\"\"\")"
    m = re.search(pattern, text)
    
    val = m.group("val")

    return val[1:-1]
    
def extract_related(text):
    m = re.search(r"related_articles\s*=\s*(\[.*?\])", text, re.DOTALL)
    raw = m.group(1)

    return ast.literal_eval(raw)

def parse_content(text):
    fields = [
        'content_id', 'chunk', 'content_title',
        'article_id', 'article_title', 'article_url',
        'article_date', 'category_name'
    ]

    extracted = {f: extract_field(text, f) for f in fields}
    extracted['related_articles'] = extract_related(text)

    if extracted['chunk']:
        extracted['chunk'] = extracted['chunk'].replace('\\n', '\n')

    return extracted

result = parse_content(str(item.content))

print(json.dumps(result, ensure_ascii=False, indent=2))

{
  "content_id": "ART_015_0005231558_chunk_0",
  "chunk": "미국 증시 전망\n\nAI 거품론 vs 대세론 시험대\n기업 영업이익률 고점 경신 등\n'상승 랠리' 올해도 이어질 듯\n\n데이터센터·전력 수요 폭증에\n에너지인프라·유틸리티株 유망\n\n뜨거웠던 비만약 열풍 이어져\n헬스케어·바이오 등 혁신 기업\n'제2 엔비디아' 될 가능성 커\n올해 미국 증시는 지난 2년간 기술주 열풍을 이끈 빅테크에 냉혹한 시험대가 될 것으로 전망된다. 이들 기업이 인공지능(AI) 부문에서 가시적 이익을 낼 수 있어야 주가 거품 논란에서 벗어나기 때문이다. 월가에선 작년보다 올해 미국의 기준금리 인하 속도가 둔화해 부채가 적고 현금 흐름이 좋은 기업에 투자자 시선이 쏠릴 것이란 예상이 나온다.\n\nAI 수익화의 원년\n골드만삭스는 최근 보고서를 통해 2026년 S&P500지수가 7000 선에 안착할 것이라는 낙관론을 내놨다. 그 근거는 AI 인프라 투자 결과물이 기업 주당순이익(EPS)으로 본격 전환되는 ‘수확의 시기’가 도래한다는 점이다.\n\n사비타 수브라마니안 뱅크오브아메리카(B",
  "content_title": "\"S&P500, 7000선 안착…돈되는 AI株 담아야\"",
  "article_id": "ART_015_0005231558",
  "article_title": "\"S&P500, 7000선 안착…돈되는 AI株 담아야\"",
  "article_url": "https://n.news.naver.com/mnews/article/015/0005231558",
  "article_date": "2026-01-01 16:13:14",
  "category_name": "세계",
  "related_articles": [
    {
      "article_id": "ART_023_0003950359",
      "title": "새해 최고 부자는 머스크 895조원... 테크 창업자가 상위권 휩쓸어",
      "published_date": "2026-01-01 16:08:15",
      "url": "https://n.news.naver.com/mnews/article/023/0003950359"
    },
    {
      "article_id": "ART_366_0001133511",
      "title": "美 국무부, 韓정보통신망법에 “중대 우려… 美 플랫폼 기업에 부정적”",
      "published_date": "2026-01-01 07:20:09",
      "url": "https://n.news.naver.com/mnews/article/366/0001133511"
    },
    {
      "article_id": "ART_056_0012096715",
      "title": "미, 베네수엘라 ‘그림자 선단’ 등 제재…“마두로 압박 계속”",
      "published_date": "2026-01-01 05:52:26",
      "url": "https://n.news.naver.com/mnews/article/056/0012096715"
    },
    {
      "article_id": "ART_025_0003493522",
      "title": "\"다카이치 대만 발언 타이밍 나빴다…중일 갈등 1년 지속될 듯\"",
      "published_date": "2025-12-31 05:00:05",
      "url": "https://n.news.naver.com/mnews/article/025/0003493522"
    },
    {
      "article_id": "ART_001_0015823340",
      "title": "\"AI 도입에 유럽 은행 일자리 5년내 20만개 위험\"",
      "published_date": "2025-12-31 22:36:15",
      "url": "https://n.news.naver.com/mnews/article/001/0015823340"
    },
    {
      "article_id": "ART_448_0000580677",
      "title": "트럼프 \"시카고·LA·포틀랜드 軍 철수…범죄 늘면 재배치\"",
      "published_date": "2026-01-01 09:44:13",
      "url": "https://n.news.naver.com/mnews/article/448/0000580677"
    },
    {
      "article_id": "ART_032_0003418544",
      "title": "미 의회, 중국군 대만 포위 훈련에 “의도적 상황 악화 행위” 비판",
      "published_date": "2025-12-31 07:40:00",
      "url": "https://n.news.naver.com/mnews/article/032/0003418544"
    },
    {
      "article_id": "ART_052_0002294961",
      "title": "뉴욕 타임스퀘어 볼 드롭 보며 백만 명 새해 맞이해...미국 건국 250주년 기념",
      "published_date": "2026-01-01 15:58:30",
      "url": "https://n.news.naver.com/mnews/article/052/0002294961"
    },
    {
      "article_id": "ART_015_0005231557",
      "title": "가치주·기술주 중심 랠리 지속…닛케이 연말 5만5000 뚫을 것",
      "published_date": "2026-01-01 16:12:19",
      "url": "https://n.news.naver.com/mnews/article/015/0005231557"
    }
  ]
}

In [12]:
def get_schema():
    with driver.session() as session:
        node_info = session.run("""
            CALL db.schema.nodeTypeProperties()
            YIELD nodeType, propertyName, propertyTypes
            RETURN nodeType, collect(propertyName) as properties
        """).data()

        rel_info = session.run('''
            CALL db.schema.relTypeProperties()
            YIELD relType, propertyName, propertyTypes
            RETURN relType, collect(propertyName) as properties
        ''').data()

        patterns = session.run('''
            MATCH (n)-[r]->(m)
            RETURN DISTINCT labels(n)[0] as source, type(r) as relationship, labels(m)[0] as target
            LIMIT 20
        ''').data()

        schema_text = '=== Neo4j Schema ===\n'

        schema_text += '\n노드 타입:\n'
        for node in node_info:
            schema_text += f"- {node['nodeType']}: {node['properties']}\n"

        schema_text += '\n관계 패턴:\n'
        for pattern in patterns:
            schema_text += f"- ({pattern['source']})-[:{pattern['relationship']}]->({pattern['target']})\n"
        
        return schema_text

neo4j_schema = get_schema()
print(neo4j_schema)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Procedure.ProcedureWarning} {category: GENERIC} {title: The query used a procedure that generated a warning.} {description: The query used a procedure that generated a warning. (The field `propertyTypes` will change output format in the next major version.)} {position: line: 2, column: 13, offset: 13} for query: '\n            CALL db.schema.nodeTypeProperties()\n            YIELD nodeType, propertyName, propertyTypes\n            RETURN nodeType, collect(propertyName) as properties\n        '
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Procedure.ProcedureWarning} {category: GENERIC} {title: The query used a procedure that generated a warning.} {description: The query used a procedure that generated a warning. (The field `propertyTypes` will change output format in the next major version.)} {position: line: 2, column: 13, offset: 13} for query: '\n            CALL db.schema.relTypeProperties()\n            YIELD relType, propertyName, propertyTypes\n            RETURN relType, collect(propertyName) as properties\n        '

=== Neo4j Schema ===

노드 타입:
- :`Article`: ['article_id', 'title', 'url', 'published_date']
- :`Content`: ['article_id', 'content_id', 'title', 'url', 'published_date', 'chunk', 'chunk_index', 'embedding']
- :`Media`: ['name']
- :`Category`: ['name']

관계 패턴:
- (Article)-[:HAS_CHUNK]->(Content)
- (Article)-[:BELONGS_TO]->(Category)
- (Media)-[:PUBLISHED]->(Article)

In [13]:
examples = [
    '''
    USER INPUT: 경제 분야의 최신 뉴스 알려주세요
    CYPHER QUERY:
    MATCH (a:Article)-[:BELONGS_TO]->(c:Category {name: "경제"})
    RETRN a.article_id, a.title, a.url, a.published_date
    ORDER BY a.published_date DESC
    LIMIT 10
    ''',
    '''
    USER INPUT: 매일경제에서 나온 최신 뉴스 3개 보여주세요
    CYPHER QUERY:
    MATCH (m:Media {name: "매일경제"})-[:PUBLISHED]->(a:Article)
    RETURN a.article_id, a.title, a.url, a.published_date
    ORDER BY a.published_date DESC
    LIMIT 3
    ''',
    '''
    USER INPUT: 2025년 11월 1일 이후에 발행된 정치 관련 기사는 몇 개나 되나요?
    CYPHER QUERY:
    MATCH (a:Article)-[:BELONGS_TO]->(c:Category)
    RETURN c.name as category, count(a) as article_count
    ORDER BY article_count DESC
    ''',
    '''
    USER INPUT: 11월 2일에 발행된 기사 중 정치 분야는?
    CYPHER QUERY:
    MATCH (a:Article)-[:BELONGS_TO]->(c:Category {name: "정치"})
    WHERE a.published_date STARTS WITH "2025-11-02"
    RETURN a.article_id, a.title, a.url, a.published_date
    ORDER BY a.published_date DESC
    ''',
]

text2cypher_retriever = Text2CypherRetriever(
    driver=driver,
    llm=llm,
    neo4j_schema=neo4j_schema,
    examples=examples,
)

In [14]:
results = text2cypher_retriever.search(query_text='정치 카테고리의 최신 기사 5개를 보여주세요')
for j, item in enumerate(results.items):
    print(f" 결과 {j+1}:")
    print(f' Content: {item.content}')
    if item.metadata:
        print(f" Metadata: {item.metadata}")

 결과 1:
 Content: <Record a.article_id='ART_366_0001133586' a.title='文 만난 조국 “李정부 성공 위한 레드팀 역할 할 것”' a.url='https://n.news.naver.com/mnews/article/366/0001133586' a.published_date='2026-01-01 15:12:07'>
 결과 2:
 Content: <Record a.article_id='ART_020_0003686138' a.title='봉하마을 참배한 정청래 “김대중 노무현 문재인의 꿈 계승”' a.url='https://n.news.naver.com/mnews/article/020/0003686138' a.published_date='2026-01-01 14:26:16'>
 결과 3:
 Content: <Record a.article_id='ART_011_0004573653' a.title='[신년사]장동혁 "국민 삶 생각하면 \'선거 승리\' 따라올 것"' a.url='https://n.news.naver.com/mnews/article/011/0004573653' a.published_date='2026-01-01 11:42:10'>
 결과 4:
 Content: <Record a.article_id='ART_015_0005231492' a.title='이혜훈 이어 유승민도?…"총리 제안 왔지만 답변 안했다"' a.url='https://n.news.naver.com/mnews/article/015/0005231492' a.published_date='2026-01-01 10:57:12'>
 결과 5:
 Content: <Record a.article_id='ART_014_0005456806' a.title='\'1억 수수 의혹\' 강선우 "어떠한 돈도 받은 적 없다"' a.url='https://n.news.naver.com/mnews/article/014/0005456806' a.published_date='2026-01-01 10:25:11'>

In [15]:
results = text2cypher_retriever.search(query_text='언론사별로 기사 개수를 알려주세요')
for j, item in enumerate(results.items):
    print(f" 결과 {j+1}:")
    print(f" Content: {item.content}")
    if item.metadata:
        print(f" Metadata: {item.metadata}")

 결과 1:
 Content: <Record media_name='연합뉴스' article_count=7>
 결과 2:
 Content: <Record media_name='머니투데이' article_count=6>
 결과 3:
 Content: <Record media_name='YTN' article_count=4>
 결과 4:
 Content: <Record media_name='한국경제' article_count=3>
 결과 5:
 Content: <Record media_name='매일경제' article_count=3>
 결과 6:
 Content: <Record media_name='한국일보' article_count=3>
 결과 7:
 Content: <Record media_name='파이낸셜뉴스' article_count=2>
 결과 8:
 Content: <Record media_name='뉴스1' article_count=2>
 결과 9:
 Content: <Record media_name='조선비즈' article_count=2>
 결과 10:
 Content: <Record media_name='서울경제' article_count=2>
 결과 11:
 Content: <Record media_name='동아일보' article_count=2>
 결과 12:
 Content: <Record media_name='조선일보' article_count=2>
 결과 13:
 Content: <Record media_name='KBS' article_count=2>
 결과 14:
 Content: <Record media_name='전자신문' article_count=2>
 결과 15:
 Content: <Record media_name='경향신문' article_count=2>
 결과 16:
 Content: <Record media_name='디지털타임스' article_count=2>
 결과 17:
 Content: <Record media_name='SBS' article_count=1>
 결과 18:
 Content: <Record media_name='아시아경제' article_count=1>
 결과 19:
 Content: <Record media_name='헤럴드경제' article_count=1>
 결과 20:
 Content: <Record media_name='블로터' article_count=1>
 결과 21:
 Content: <Record media_name='한경비즈니스' article_count=1>
 결과 22:
 Content: <Record media_name='뉴시스' article_count=1>
 결과 23:
 Content: <Record media_name='SBS Biz' article_count=1>
 결과 24:
 Content: <Record media_name='kbc광주방송' article_count=1>
 결과 25:
 Content: <Record media_name='헬스조선' article_count=1>
 결과 26:
 Content: <Record media_name='코메디닷컴' article_count=1>
 결과 27:
 Content: <Record media_name='이데일리' article_count=1>
 결과 28:
 Content: <Record media_name='중앙일보' article_count=1>
 결과 29:
 Content: <Record media_name='TV조선' article_count=1>